### ISSUE TITLE
Use separate classifiers, and only try to predict the negative ones

### ISSUE THREAD

**Issue by rogeriochaves** [fake-news-detector/robinho#1]
So, currently Robinho uses a very naive approach to try classifying news articles in different categories, but not the same methodology will work for every class, for example, to identify fake news, we really need the full article text, while click baits, as the name says, only needs the title.

My idea is the have separate classifiers, and only for the *negative* classes, what I mean by that is:

**Positive Classes**: Legitimate, Satire, Not news ([api#1](https://github.com/fake-news-detector/api/issues/1) and [extension#3](https://github.com/fake-news-detector/extension/issues/3))

**Negative Classes**: Fake News, Click Bait, Extremely Biased

The reasons of focusing only on negative classes are:

- We only want to warn our users and grab their attention if it is something negative, else if we warn for everything they might start overlooking it and get annoyed
- Like when you are trying to identifying cancer, it is much easier to search for things that might indicate that something is cancer than also trying to find out everything else it could be, so instead of searching for legitimate words, we only search for fake news ones
- Like cancer, it is better to give false positives (mark something legit as fake news) than the other way around, it might get some people angry, but at least will generate awareness

What are positive classes used for then? Well, to balance the negative votes, if people start marking something as Fake News while it is not, other people can mark it as Legit to counter-balance it, and we can be more aware when using this data for training robinho

# What values does it brings

- Better classification for the user
- Less visual pollution for the user
- Easier to for focus research of individual categories classification

**Comment by carlos19silva94** [comment]
can you give me your email?

**Comment by rogeriochaves** [comment]
@carlos19silva94 rogeriocfj (at) gmail.com

**Comment by rogeriochaves** [comment]
I've made a split in #1, now the classifiers can evolve separately I hope, but first we need to get more data before we can actually work in discovering which algorithm works best for each classes

**Comment by rogeriochaves** [comment]
This was solved on the API, no need to change robinho
